### ISSUE TITLE
Performance bug with Dask

### ISSUE THREAD

**Issue by AlbertDeFusco** [datacamp/ipython_nose#3]
https://github.com/datacamp/ipython_nose/blob/33916f71be848d72fbfda26ef4d106f5afee5f63/ipython_nose.py#L250

There is a performance regression when using `%%nose` magic with Dask DataFrames.

To begin, Dask DataFrames *do not know* their size, it must be computed by reading all of the rows.* This could take minutes or hours for large datasets.

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.read_csv('src/311/311_Service_Requests_from_2012.csv', dtype='object')

In [3]: %%time
   ...: if df == df:
   ...:     print('yes')
   ...: 
yes
CPU times: user 29.1 s, sys: 3.77 s, total: 32.8 s
Wall time: 24.5 s
```

Could the `is` keyword be used here instead?

```python
In [4]: %%time
   ...: if df is df:
   ...:     print('yes')
   ...: 
yes
CPU times: user 10 µs, sys: 9 µs, total: 19 µs
Wall time: 22.2 µs
```

See [this notebook](https://anaconda.org/defusco/ipython_nose/notebook) for full traceback after interrupt.

You'll notice that L250 from `ipython_nose.py` triggers `__len()__`, which is what happens during Input 3 above when comparing DataFrames *line-by-line*.

* There are a few cases where they do, but it should not be assumed.

**Comment by machow** [comment]
Hey @AlbertDeFusco, sorry for the delay, I was on vacation when this was opened. It definitely looks like `==` should be changed to `is`. I'll plan to update on here and on DataCamp this week.

cc @rv2e
